### ISSUE TITLE
Error parsing script:

### ISSUE THREAD

**Issue by Koku0** [CraftTweaker/CraftTweaker-Documentation#130]
Here is the script: (What's wrong with it?)

import crafttweaker.item.IItemStack;
import mods.jei.JEI;

var bronze as IItemStack;
var table as IItemStack;
var tooltable as IItemStack;
var saw as IItemStack;
var log as IItemStack;
var workb as IItemStack;

bronze = <ore:ingotBronze>;
table = <ore:worktableShelf>;
tooltable = <tconstruct:tooltables>;
saw = <microblockcbe:saw_stone>;
log = <ore:logSplit>;
workb = <ore:workbench>;

recipes.addShaped(tconstruct:tools/table/crafting_station,tooltable,
[[bronze,table,bronze],[log,saw,log]]);
recipes.removeShapeless(tooltable, workb);

**Comment by kindlich** [comment]
Let's see what's wrong here:

A) This question belongs into the discord server rather than the CrT issue tracker, and even less into the CrT wiki issue tracker.
B) You did not state what is not working nor what the log tells you
C) You did not use code blocks so.I cannot see whther the missing `<>` derive from GH trying to appl Markdown or if you actually forgot them.
D) You declare IItemStack variables but assign IOreDictEntry objects in some cases. Why split declaration and assignment.
E) You did not put the recipe name in `""`, also the colon is kinda useless there since CrT recipes will always in the `crafttweaker` domain
F) Your call to removeShapeless is incorrect as it expects an array

**Comment by Koku0** [comment]
Oh shit my bad, sorry.

**Comment by kindlich** [comment]
Closing this since it seems to be resolved, if not, just answer and I'll reopen it.
