### ISSUE TITLE
Item conditions don't work with ore dictionary

### ISSUE THREAD

**Issue by Winddbourne** [CraftTweaker/CraftTweaker-Documentation#211]
It's very simple . . . I want the recipe to use the ore dictionary since I have a TON of hatchets and axes in my pack that I want the recipe to work with. I ALSO want the recipe to ignore damage. 

This should be a simple matter of using the ore dictionary and then adding the ".anyDamage()" after the item. The problem is it doesn't work. 

![2019-09-25_12 34 55](https://user-images.githubusercontent.com/24589533/65621219-558bfb80-df91-11e9-9b36-327f8553f792.png)

I've tried every way I can figure out, including simply putting .* after the ore dictionary entry. None of it has worked. That's a huge problem since if I can't use a damaged tool the recipe is broken, and if I have to put in separate recipes for EVERY ax and hatchet in my patch it's simply going to take forever . . . that's why we have ore dictionary in the first place. lol

I'm extremely frustrated. 

recipes.addShapeless(<primal:worktable_shelf>, [<ore:toolHatchet>.anyDamage(), <ore:logWood>]);

**Comment by kindlich** [comment]
AnyDamage is only available to IItemStack, since it is defined in there.
If you want the item in the oredict to accept any damage value you need to add the version without damage value to the oredict e.g. by using `<ore:toolHatchet>.add(<my:hatched:*>);` with the wildcard damage value

**Comment by Winddbourne** [comment]
Ewww . . . that would have me inputting every ax and hatchet, or whatever tool,  to the ore dictionary with the wildcard attachment and then it would mean that damaged tools would work for ANY recipe that used the ore dictionary. 

I guess it's still better than having to add each ax and hatchet repeatedly for every type of workbench but . . . ::shivers:: It's definitely a flawed workaround.

**Comment by kindlich** [comment]
Alternatively, you could create yourself a compound ingredient like this:

```zenscript
var allMyHatchets = null as IIngredient;

for item in <ore:toolHatchet>.items {
    if(isNull(allMyHatchets)) {
        allMyHatchets= item.anyDamage();
    } else {
        allMyHatchets|= item.anyDamage();
    }
}

//Use the variable allMyHatchets now
```

**Comment by Winddbourne** [comment]
oh! I'm glad I waited to get my wife from work before I started coding in a new ore dictionary set. If that works it looks way more doable.  

The other option is simple enough, but it's monotonous as there are probably 40+ different entries I'd need to code from various mods and afterward I'd have to go back and add things any time someone updated their code to include a new ax. 

Primal Core is awesome but they certainly do use a different method for creating that first crafting bench out of a log.  They do a great job at incorporating all the vanilla logs and even giving them their own textures but the moment I add a new tree to the pack I have to figure out a way to support it or risk players getting frustrated when the first ten trees they chop down don't work with the recipe. lol

**Comment by Winddbourne** [comment]
Hmmm . . . I may have to do it the hard way after all. Probably starting with the hatchets since there are less of them than axes, and using a NEW ore dictionary entry so I can separate out axes/hatchets that are for this recipe from everything else where I may not want damaged tools to work.

**Comment by kindlich** [comment]
You need to import IIngredient, I assumed you already did

**Comment by Winddbourne** [comment]
I had it, but removed it because I was getting "null has not operators" . . . which added to the list of errors and completely frustrated me.  Adding it back puts me back where I was. lol

Now I need to figure out how to get rid of that error. This is what I currently have:

import crafttweaker.item.IIngredient;
var allMyHatchets = null as IIngredient;

for item in <ore:toolHatchet>.items {
    if(isNull(allMyHatchets)) {
        allMyHatchets= item.anyDamage();
    } else {
        allMyHatchets|= item.anyDamage();
    }
}

**Comment by Riernar** [comment]
Hi @Winddbourne , I'm not very knowledgable about CrT and JEI, but did you check if the recipe actually worked ? I vaguely remember something about JEI only showing the first item of OR-ed `IIngredient` in CrT.
Also, make sure the hatchets are added to the oreDictionary *before* CrT executes the scripts. Some mod do late registration which prevent knowing some items' oreDict entries in zs. For testing purposes, maybe you can add a tooltip to all hatchets you find in your loop

Hope this helps !

**Comment by Winddbourne** [comment]
Thanks. I should have closed this. I got the code working a while back and should have closed this out. I appreciate the help. :)

**Comment by Riernar** [comment]
Glad it worked out !
Would you mind posting your solution, to help those with the same issue that would find this issue thread ?

**Comment by Winddbourne** [comment]
Sure. Removing the else got the code to work to some extent but it only auto loaded one item. The fix was to add a second recipe that simply used the Axe ore dictionary entry and have it call up the object. 

The ironic thing is that once I had it working I didn't like the fact that it would affect all my axes in any recipe I used the ore dictionary on and went back and made a new ore dictionary entry anyway. It was more tedious but safer. lol

**Comment by Riernar** [comment]
@Winddbourne 
I finally understand your first post. I think you misunderstood kindlich's code - that's why removing the else statement made the code register only the first item. Let me explain:
*NOTE: I have put some links to specific part of CrT documentation that explain better what I'm talking about*

First thing first, the `|` in the original code does stand for `|` and *not* for `!`. The code
```
allMyHatchets|= item.anyDamage();
```
is shorthand for
```
allMyHatchets = allMyHatchets | item.anyDamage();
```
The `|` operator, on `IIngredients`, returns a new `IIngredient` that accepts either of the two combined ingredients - hence its name, [combined IIngredient (documentation)](https://docs.blamejared.com/1.12/en/#Vanilla/Variable_Types/IIngredient/#or-ing-an-iingredient).

Now you want the code to construct something equivalent to
```
<ore:toolHatchet>.items[0].anyDamage() | ... | <ore:toolHatchet>.items[N].anyDamage();
```
That is: accept any item in `<ore:toolHatchet>.items`, whetever its damage.

Note that types are crucial here:
+ `<ore:toolHatchet>.items[0]` is an [`IItemStack`](https://docs.blamejared.com/1.12/en/#Vanilla/Items/IItemStack/), and therefore supports `.anyDamage()`
+ `<ore:toolHatchet>` is an [`IOreDictEntry`](https://docs.blamejared.com/1.12/en/#Vanilla/OreDict/IOreDictEntry/#ioredictentry) and *doesn't have* an `anyDamage()` method.
+ [`IItemStack`](https://docs.blamejared.com/1.12/en/#Vanilla/Items/IItemStack/) objects [*are* `IIngredient`](https://docs.blamejared.com/1.12/en/#Vanilla/Items/IItemStack/#extending-iingredient) and therefore supports `IIngredient` [OR-ing feature](https://docs.blamejared.com/1.12/en/#Vanilla/Variable_Types/IIngredient/#or-ing-an-iingredient).

So the trick is to get all `IItemStack`s in the `IOreDictEntry`, use the `anyDamage()` method on all of them and combine the resulting conditioned IItemStack into a combined IIngredient.

 Since you have to start from somewhere, you first set `allMyHatchets` to `null`. Then, in the loop, you test:
+ if `allMyHatchet` is null (i.e. we are handling the first item), you just *set* `allMyHatchet` to the `IitemStack`, that is an `IIngredient`
+ else (i.e. `allMyHatchet` already contains IIngredients), you accept any previously accepted item, or the new one, whatever its damage

By removing the else statement, you removed the second part. The code became: list all item in `<ore:toolHatchet>.items`, and store the first one in `allMyHatchet` - which is why it only loaded the first.

As to why it didn't work when you still had the else block, that's because (i presume) you wrote `allMyHatchets != item` instead of `allMyHatchets |= item`. The first expression is just an inequality comparison between the two variable, which while perfectly valid, doesn't *change* `allMyHatchet` as the OR-SET operator would have.

Finally, it seems weird that you managed to get it working with two recipes - seems like a bug in CrT to me, but i'll have to test it.


Hopes this clarifies :)

**Comment by Winddbourne** [comment]
Thanks, this makes me wish I still had the original code to double-check for typos. I think I actually just copied and pasted the original code, but there is a chance I did screw it up that way. Your answer makes a lot of sense and I'd love to go back to that old code and really tear into it. :)

**Comment by Riernar** [comment]
That would be interesting, indeed ! Anyway, what is important is that you get it to work.
I'd like to see your code if you don't mind, because I tried doing your two recipes trick and it doesn't seem to work :/

However, I just tested the original code, and I *do* get a `null has not operator`, which is strange.

The fix is to initialize to something other than null:

```zenscript
var allMyHatchet = <minecraft:stone> as IIngredient;

for hatchet in <ore:toolHatchet>.items {
    if(allMyHatchet has <minecraft:stone> { #test if it is stone rather than null
        allMyHatchet = hatchet.anyDamage().transformDamage();
    } else {
        allMyHatchet |= hatchet.anyDamage().transformDamage();
    }
}

// Use allMyHatchets
```

I think this is a bug in CrT, I'll report it
