### ISSUE TITLE
[Documentation] Documentation about Thermal Expansion Augments missing (except for Redstone Furnace)

### ISSUE THREAD

**Issue by evertn** [CraftTweaker/CraftTweaker-Documentation#234]
I noticed there is only documentation about the Redstone Furnace's Pyrolitic Conversion. Does this mean the other augments are not available, or do they work in a similar way?

**Comment by kindlich** [comment]
When ModTweaker's Thermal Expansion Integration was written, most of the API methods TE offered at that time were exposed to ZS.

If TE now has more augments or otherwise expanded its API, this would first need to be added to ModTweaker before appearing in the wiki whatsoever,

You could open an issue at the ModTweaker issue tracker, but I do not know if Jared has the time to work in MoT 1.12 anytime soon.
<https://github.com/jaredlll08/ModTweaker/issues>
