### ISSUE TITLE
Items not accepted in potion slots

### ISSUE THREAD

**Issue by Temenat** [CraftTweaker/CraftTweaker-Documentation#324]
I tried to add a brewing recipe that requires Dragon Breath in the potion slots, but I' ve noticed that it' s impossible to insert it in the potion slots ingame. The wiki page for brewing recipes has example recipes that take bedrock and gold blocks as lower slot inputs so it can be a little confusing in my opinion.

**Comment by kindlich** [comment]
Since I don't know your script I can't help you. I can only tell you that the examples in the wiki work fine.
Be careful, the brewing stand only accepts stack sizes of 1 for the three potion slots.
You can's use a larger stack and rightclick, you need to split the stack in your inventory and drag a stack with only one item up there.

![image](https://user-images.githubusercontent.com/10351787/90048193-75c0c800-dcd3-11ea-8b7c-c45d6d35b109.png)

**Comment by Temenat** [comment]
Oh... I right clicked with a stack of items, that was the problem. I didn'
t know about the fact that it only works with single items. Well I guess
everything works correctly then, thank you very much for your answer ;)
