### ISSUE TITLE
How to remove Smithing Table Recipes with Eternal Stella

### ISSUE THREAD

**Issue by SharkieTV** [CraftTweaker/CraftTweaker-Documentation#480]
Hi, I'm trying to figure out how to remove the recipe Glass Sword from Twilight Forest with Eternal Stella from the Smithing Table. I tried all the things in the Wiki and its just not working.

**Comment by jaredlll08** [comment]
What have you tried?

I also have absolutely zero idea what anything you have mentioned is, so a screenshot would help

**Comment by SharkieTV** [comment]
This sword is suppose to be one hit and breaks because of 40 damage but you can apply Eternal Stella to make it Indestructible.
![image](https://user-images.githubusercontent.com/79353591/137566525-90e051fb-0e68-4cd1-93e1-62f591df49f4.png)

**Comment by SharkieTV** [comment]
<item:twilightforest:glass_sword>.withTag({Enchantments: [{lvl: 1 as short, id: "forbidden_arcanus:indestructible" as string}]})

**Comment by SharkieTV** [comment]
It didnt work but let me restart incase the /reload didnt work.
Also poggers, didnt know your South African! Me too.

**Comment by jaredlll08** [comment]
So I just took a look at the code, it seems that Forbidden Arcanus adds Eternal Stella as a single recipe with no output (the output is calculated dynamically at a later point), which is why the `remove` call didn't work.

So you can remove the recipe via its name (which is `forbidden_arcanus:apply_indestructible_enchantment`), but it would remove the system as whole, so no recipes would use Eternal Stella. 
Unfortunately you can't remove a single item from the system unless unless Forbidden Arcanus added a config for it.

If you want to remove it by it's name:
```zenscript
smithing.removeByName("forbidden_arcanus:apply_indestructible_enchantment");
```

It would need a CraftTweaker update, (which would have to happen sometime this weekend), but I could add a way to re-implement the Eternal Stella system using a script file.

If that interests you, join the discord (https://discord.blamejared.com) so we can talk about it there

For now I am going to close this just because the base issue is kinda solved (the recipe can be removed, it just removes *all* Eternal Stella recipes).

**Comment by SharkieTV** [comment]
Yeah removing everyhting would be a pain, if you can implement it that be great! I joined the Discord

**Comment by jaredlll08** [comment]
Update:
The mod has a tag blacklist feature, so you can do:
```
<tag:items:forbidden_arcanus:indestructible_blacklisted>.add(<item:twilightforest:glass_sword>);
```
to remove items from it
