### ISSUE TITLE
Documentation missing for LootTableIdLootCondition

### ISSUE THREAD

**Issue by Fydar** [CraftTweaker/CraftTweaker-Documentation#581]
Phew, I spent many hours trying to figure out how to condition my loot modifiers to only work on specific tables for 1.20.1!

`LootTableIdLootCondition` is missing from the documentation 😅

Eventually I searched the source repo and [found a dev script](https://github.com/CraftTweaker/CraftTweaker/blob/bb99e07b07b3c6b867ed95d783dbb9d227c9366d/dev_scripts/loot/loot_table_id_conditions.zs#L10) I used as an example (as the default `/ct examples` doesn't include it either).

**Comment by kindlich** [comment]
Hey there, 

the most likely reason why you didn't find it on the docs is because that condition only exists for forge, but not for fabric in 1.20.1.
That means you'll have to look in Forge/Loot and not in Vanilla/Loot.

https://docs.blamejared.com/1.20.1/en/forge/api/loot/condition/LootTableIdLootCondition

**Comment by Fydar** [comment]
You're damn right! Thanks for pointing me in the right direction.
