### ISSUE TITLE
Expand ContentTweaker documentation.

### ISSUE THREAD

**Issue by The-Arcanian** [CraftTweaker/CraftTweaker-Documentation#75]
ContentTweaker documentation only gives enough information for making standard blocks. But gives no information on how to make something like stairs or slabs. And the jsons are not explained at all.

**Comment by Wissi** [comment]
Like your idea of: 

> You're able to create a staged modpack in faster times and with less hassle.

Any way you can make the documentation available here in the Github Wiki section at least for now? 
Along with the examples you mention in the Curse page?
Since the part of: "Documentation can be found in this PR on the CraftTweaker Doc Repo."
That PR has been there for more that 20 days (I know it's all on CraftTweaker devs part now).
Having the documentation and the examples available here would be awesome (and non dependent on other devs?)

The cherry on top would be a video.     :-0
Thanks for your contributions in making this easier for all.

**Comment by kindlich** [comment]
@The-Arcanian Last time I checked, CoT didn't allow for stairs and slabs.

@Wissi That PR you are mentioning was revieved 19 days ago and changes were requested. If those aren't going to be resolved we won't merge it.


As always, this wiki is open source, you can always fork it using GH or clone it using your own git implementation and add examples yourself if you want to (I can even guide you through the process of setting up a locally working version of mkdocs though I'd prefer you joining jared's discord for that as I don't really like writing so much in issue messages that is unrelated to the issue itself)
