### ISSUE TITLE
Submit to Crowdin to help with translations?

### ISSUE THREAD

**Issue by LasmGratel** [CraftTweaker/CraftTweaker-Documentation#95]
https://crowdin.com/page/open-source-project-setup-request

Just like the way [SpongeDocs](https://docs.spongepowered.org) do.

Also, we, [CFPAOrg](https://github.com/CFPAOrg) are willing to translate and making progress on advertising CraftTweaker script development.

**Comment by NanamiArihara** [comment]
Or you will just be filling the form and let me maintain registered Crowdin project 🤔

**Comment by kindlich** [comment]
Hello NanamiArihara,

I do not know much about Crowdin but from what I've seen so far do not know if it is suitable for this documentation project:

We are using ReadTheDocs (RTD) to assemble the mkdocs project and display it.
Unfortunately, RTD expects one branch/repository per language, and not one branch containing all translations.
I have not found a way of setting RTD to use one branch (master) as translation source and export the built translations to several branches (master_zh-CN, master_de or translation_de,...).
Do you know if that is possible to do using crowdin?
Otherwise we'd have to change the whole project setup (and maybe even need to host the wiki ourselves).

Also, feel free to ping me up/DM me on discord (@kindlich#9060).

**Comment by comradekingu** [comment]
@kindlich Never submit to Crowdin. Fight spying and tracking where it exists. ;)
Weblate is a libre software alternative that has actually gratis hosting for libre software, as opposed to only allowing non-commercial libre software projects apply.

**Comment by kindlich** [comment]
@comradekingu 
Thank you for your suggestion.
We are already using Crowdin at the moment.

Truth be told, some of its integrations aren't the way we envisioned them, but it works out more or less.

To be frank, I care less about _where_ the documentation pages are translated than being able to translate them at all and having a way for our CI to create the docs pages in the different languages.
Switching would mean spending time on getting to know a new platform for changing something that is (more or less) working atm. Also, it would mean that the current translators need to switch platforms as well.

In any way, feel free to send a PM on Discord or another medium of your choice and we can discuss this further.
My Discord tag is `kindlich#9060`

**Comment by jaredlll08** [comment]
Crowdin has been supported for a long time.
